### ISSUE TITLE
Add support for multiple IRC networks

### ISSUE THREAD

**Issue by flexiondotorg** [shelson/willbot_irc_bridge#6]
It would be very useful if `willbot_irc_bridge` could support multiple IRC networks. Most of what I want to bridge is on Freenode, but as I Debian maintainer, I also use OFTC :-)

**Comment by shelson** [comment]
I'll have a think about how this could be done - it would require dealing with the hipchat->irc mappings more explicitly than just channelname==channelname. Definitely not impossible though.
